### ISSUE TITLE
IATA NDC schemas 16.2 not working v2

### ISSUE THREAD

**Issue by nerijusza** [goetas-webservices/xsd2php#40]
This issue is related to https://github.com/goetas-webservices/xsd2php/issues/38

Updated via composer to version "^0.3".

Generated required data for tests via commands:
vendor/bin/xsd2php convert config.yml xsd/SeatAvailabilityRQ.xsd
vendor/bin/xsd2php convert config.yml xsd/OrderCancelRQ.xsd
vendor/bin/xsd2php convert config.yml xsd/ServiceListRQ.xsd

Rerun same tests. Good news, that issue in #38 is fixed(files exists now). But now got different error. test1.php, test2.php, test3.php:
PHP Fatal error:  Uncaught exception 'JMS\Parser\SyntaxErrorException' with message 'Expected T_NAME, but got "\" of type T_NONE at beginning of input.' in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php:118

test4.php after update works now(was not working before).

test2a.php works. Removed xml part from file "test2.php" that was failing.

Pleasee see attached files:
[test.zip](https://github.com/goetas-webservices/xsd2php/files/1247977/test.zip)

I think issue is not fixed properly.

Here is all fatal trace:
------------------------------------------------------------------------
PHP Fatal error:  Uncaught exception 'JMS\Parser\SyntaxErrorException' with message 'Expected T_NAME, but got "\" of type T_NONE at beginning of input.' in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php:118
Stack trace:
#0 /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php(73): JMS\Parser\AbstractParser->syntaxError('T_NAME')
#1 /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/TypeParser.php(84): JMS\Parser\AbstractParser->match(1)
#2 /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php(49): JMS\Serializer\TypeParser->parseInternal()
#3 /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Metadata/PropertyMetadata.php(112): JMS\Parser\AbstractParser->parse('\\AnyType')
#4 /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/YamlDriver.php(123): JMS\Serializer\Metadata\PropertyMetadata->setType('\\AnyType')
#5 /home/www/nerijus/goetas/vendor/jms/metadata/src/Metadata/Driver/Abstr in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php on line 118

Fatal error: Uncaught exception 'JMS\Parser\SyntaxErrorException' with message 'Expected T_NAME, but got "\" of type T_NONE at beginning of input.' in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php on line 118

JMS\Parser\SyntaxErrorException: Expected T_NAME, but got "\" of type T_NONE at beginning of input. in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php on line 118

Call Stack:
    0.0001     222472   1. {main}() /home/www/nerijus/goetas/test1.php:0
    0.2842    2476632   2. JMS\Serializer\Serializer->deserialize() /home/www/nerijus/goetas/test1.php:84
    0.3019    2607776   3. PhpOption\Some->map() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Serializer.php:131
    0.3019    2607952   4. call_user_func:{/home/www/nerijus/goetas/vendor/phpoption/phpoption/src/PhpOption/Some.php:89}() /home/www/nerijus/goetas/vendor/phpoption/phpoption/src/PhpOption/Some.php:89
    0.3019    2608096   5. JMS\Serializer\Serializer->JMS\Serializer\{closure}() /home/www/nerijus/goetas/vendor/phpoption/phpoption/src/PhpOption/Some.php:89
    0.3022    2611784   6. JMS\Serializer\Serializer->visit() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Serializer.php:128
    0.3022    2614848   7. JMS\Serializer\GraphNavigator->accept() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Serializer.php:193
    0.6581    4144104   8. JMS\Serializer\XmlDeserializationVisitor->visitProperty() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php:266
    0.6581    4144280   9. JMS\Serializer\GraphNavigator->accept() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:295
    0.6944    4343168  10. JMS\Serializer\XmlDeserializationVisitor->visitProperty() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php:266
    0.6945    4343392  11. JMS\Serializer\GraphNavigator->accept() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:266
    0.6945    4343608  12. JMS\Serializer\XmlDeserializationVisitor->visitArray() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php:152
    0.6946    4344456  13. JMS\Serializer\GraphNavigator->accept() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:190
    0.7565    4569352  14. JMS\Serializer\XmlDeserializationVisitor->visitProperty() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php:266
    0.7565    4569528  15. JMS\Serializer\GraphNavigator->accept() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/XmlDeserializationVisitor.php:295
    0.7565    4569792  16. Metadata\MetadataFactory->getMetadataForClass() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/GraphNavigator.php:211
    0.7569    4585472  17. Metadata\Driver\DriverChain->loadMetadataForClass() /home/www/nerijus/goetas/vendor/jms/metadata/src/Metadata/MetadataFactory.php:103
    0.7569    4585472  18. Metadata\Driver\AbstractFileDriver->loadMetadataForClass() /home/www/nerijus/goetas/vendor/jms/metadata/src/Metadata/Driver/DriverChain.php:38
    0.7570    4585608  19. JMS\Serializer\Metadata\Driver\YamlDriver->loadMetadataFromFile() /home/www/nerijus/goetas/vendor/jms/metadata/src/Metadata/Driver/AbstractFileDriver.php:28
    0.7628    4608248  20. JMS\Serializer\Metadata\PropertyMetadata->setType() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Metadata/Driver/YamlDriver.php:123
    0.7628    4608248  21. JMS\Parser\AbstractParser->parse() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Metadata/PropertyMetadata.php:112
    0.7628    4609072  22. JMS\Serializer\TypeParser->parseInternal() /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php:49
    0.7628    4609120  23. JMS\Parser\AbstractParser->match() /home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/TypeParser.php:84
    0.7628    4609464  24. JMS\Parser\AbstractParser->syntaxError() /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php:73

**Comment by goetas** [comment]
Can you make a zip with your yaml files?

On 24 Aug 2017 09:05, "nerijusza" <notifications@github.com> wrote:

This issue is related to #38
<https://github.com/goetas-webservices/xsd2php/issues/38>

Updated via composer to version "^0.3".

Generated required data for tests via commands:
vendor/bin/xsd2php convert config.yml xsd/SeatAvailabilityRQ.xsd
vendor/bin/xsd2php convert config.yml xsd/OrderCancelRQ.xsd
vendor/bin/xsd2php convert config.yml xsd/ServiceListRQ.xsd

Rerun same tests. Good news, that issue in #38
<https://github.com/goetas-webservices/xsd2php/issues/38> is fixed(files
exists now). But now got different error. test1.php, test2.php, test3.php:
PHP Fatal error: Uncaught exception 'JMS\Parser\SyntaxErrorException' with
message 'Expected T_NAME, but got "" of type T_NONE at beginning of input.'
in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/
Parser/AbstractParser.php:118

test4.php after update works now(was not working before).

test2a.php works. Removed xml part from file "test2.php" that was failing.

Pleasee see attached files:
test.zip
<https://github.com/goetas-webservices/xsd2php/files/1247977/test.zip>

I think issue is not fixed properly.
Here is all fatal trace:

PHP Fatal error: Uncaught exception 'JMS\Parser\SyntaxErrorException' with
message 'Expected T_NAME, but got "" of type T_NONE at beginning of input.'
in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/
Parser/AbstractParser.php:118
Stack trace:
#0 /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php(73):
JMS\Parser\AbstractParser->syntaxError('T_NAME')
#1 <https://github.com/goetas-webservices/xsd2php/issues/1>
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/TypeParser.php(84):
JMS\Parser\AbstractParser->match(1)
#2 <https://github.com/goetas-webservices/xsd2php/pull/2>
/home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php(49):
JMS\Serializer\TypeParser->parseInternal()
#3 <https://github.com/goetas-webservices/xsd2php/issues/3>
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Metadata/PropertyMetadata.php(112):
JMS\Parser\AbstractParser->parse('\AnyType')
#4 <https://github.com/goetas-webservices/xsd2php/pull/4>
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/Metadata/Driver/YamlDriver.php(123): JMS\Serializer\Metadata\
PropertyMetadata->setType('\AnyType')
#5 <https://github.com/goetas-webservices/xsd2php/issues/5>
/home/www/nerijus/goetas/vendor/jms/metadata/src/Metadata/Driver/Abstr in
/home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php
on line 118

Fatal error: Uncaught exception 'JMS\Parser\SyntaxErrorException' with
message 'Expected T_NAME, but got "" of type T_NONE at beginning of input.'
in /home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php
on line 118

JMS\Parser\SyntaxErrorException: Expected T_NAME, but got "" of type T_NONE
at beginning of input. in /home/www/nerijus/goetas/
vendor/jms/parser-lib/src/JMS/Parser/AbstractParser.php on line 118

Call Stack:
0.0001 222472 1. {main}() /home/www/nerijus/goetas/test1.php:0
0.2842 2476632 2. JMS\Serializer\Serializer->deserialize()
/home/www/nerijus/goetas/test1.php:84
0.3019 2607776 3. PhpOption\Some->map() /home/www/nerijus/goetas/
vendor/jms/serializer/src/JMS/Serializer/Serializer.php:131
0.3019 2607952 4. call_user_func:{/home/www/nerijus/goetas/vendor/
phpoption/phpoption/src/PhpOption/Some.php:89}() /home/www/nerijus/goetas/
vendor/phpoption/phpoption/src/PhpOption/Some.php:89
0.3019 2608096 5. JMS\Serializer\Serializer->JMS\Serializer{closure}()
/home/www/nerijus/goetas/vendor/phpoption/phpoption/
src/PhpOption/Some.php:89
0.3022 2611784 6. JMS\Serializer\Serializer->visit()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/Serializer.php:128
0.3022 2614848 7. JMS\Serializer\GraphNavigator->accept()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/Serializer.php:193
0.6581 4144104 8. JMS\Serializer\XmlDeserializationVisitor->visitProperty()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/GraphNavigator.php:266
0.6581 4144280 9. JMS\Serializer\GraphNavigator->accept()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/
XmlDeserializationVisitor.php:295
0.6944 4343168 10. JMS\Serializer\XmlDeserializationVisitor->visitProperty()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/GraphNavigator.php:266
0.6945 4343392 11. JMS\Serializer\GraphNavigator->accept()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/
XmlDeserializationVisitor.php:266
0.6945 4343608 12. JMS\Serializer\XmlDeserializationVisitor->visitArray()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/GraphNavigator.php:152
0.6946 4344456 13. JMS\Serializer\GraphNavigator->accept()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/
XmlDeserializationVisitor.php:190
0.7565 4569352 14. JMS\Serializer\XmlDeserializationVisitor->visitProperty()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/GraphNavigator.php:266
0.7565 4569528 15. JMS\Serializer\GraphNavigator->accept()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/
XmlDeserializationVisitor.php:295
0.7565 4569792 16. Metadata\MetadataFactory->getMetadataForClass()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/GraphNavigator.php:211
0.7569 4585472 17. Metadata\Driver\DriverChain->loadMetadataForClass()
/home/www/nerijus/goetas/vendor/jms/metadata/src/
Metadata/MetadataFactory.php:103
0.7569 4585472 18. Metadata\Driver\AbstractFileDriver->loadMetadataForClass()
/home/www/nerijus/goetas/vendor/jms/metadata/src/
Metadata/Driver/DriverChain.php:38
0.7570 4585608 19.
JMS\Serializer\Metadata\Driver\YamlDriver->loadMetadataFromFile()
/home/www/nerijus/goetas/vendor/jms/metadata/src/Metadata/Driver/
AbstractFileDriver.php:28
0.7628 4608248 20. JMS\Serializer\Metadata\PropertyMetadata->setType()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/Metadata/Driver/YamlDriver.php:123
0.7628 4608248 21. JMS\Parser\AbstractParser->parse()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/Serializer/Metadata/
PropertyMetadata.php:112
0.7628 4609072 22. JMS\Serializer\TypeParser->parseInternal()
/home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/
Parser/AbstractParser.php:49
0.7628 4609120 23. JMS\Parser\AbstractParser->match()
/home/www/nerijus/goetas/vendor/jms/serializer/src/JMS/
Serializer/TypeParser.php:84
0.7628 4609464 24. JMS\Parser\AbstractParser->syntaxError()
/home/www/nerijus/goetas/vendor/jms/parser-lib/src/JMS/
Parser/AbstractParser.php:73

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/goetas-webservices/xsd2php/issues/40>, or mute the
thread

**Comment by nerijusza** [comment]
You mean files generated by 
vendor/bin/xsd2php convert config.yml xsd/SeatAvailabilityRQ.xsd
vendor/bin/xsd2php convert config.yml xsd/OrderCancelRQ.xsd
vendor/bin/xsd2php convert config.yml xsd/ServiceListRQ.xsd

Here is it(php classess and metadata yml):
[soap.zip](https://github.com/goetas-webservices/xsd2php/files/1248429/soap.zip)

If config.yml, that was used for generation it is already attached in first post zip:
[test.zip](https://github.com/goetas-webservices/xsd2php/files/1247977/test.zip)

**Comment by goetas** [comment]
The IATA schemas are using the xsd any types... this mean that you have to handle it with custom handlers. check it on https://github.com/goetas-webservices/xsd2php#dealing-with-xsdanytype-or-xsdanysimpletype  how to do it.

Closing as the problem looks solved to me

**Comment by nerijusza** [comment]
After your comment thought you are right. But now looked to this issue once more. And noticed that "xsd:any" is used in schemas only for three data types, which are not used in my provided not working samples. Can you recheck this issue?

**Comment by goetas** [comment]
@nerijusza Wwhen the XSD needs to be parsed (because some type in it is used [ not necessarily an xsd:anyType ] ) then the configuration is necessary.

the handler might be not necessary if the "anyType" is effectively never used.



in your example, all this classes are using an "anyType":

```
BagAllowanceDimensionType.DimensionsAType
BankAccountMethodType
CompanyList
Contacts.ContactAType.NameAType
Contacts.ContactAType
DetailCurrencyPriceType
ExitPositionType.RowsAType.FirstAType
ExitPositionType.RowsAType.LastAType
FlightDisplayPricingMethod
FQTVProgramCoreType.TierAType
FQTVProgramCoreType.TierAType
FQTVProgramCoreType.TierAType
GeographicSpecificationType.CoordinatesAType.CoordinateRadiusAType
MarketingCarrierFlightType
MediaAttachmentType
NoticesGrp
OfferPriceLeadType
OrderCoreType.OriginalOrderAType.PriceQuotesAType.PriceQuoteAType.SourceAType
OrderCoreType.OriginalOrderAType.PriceQuotesAType.PriceQuoteAType.SourceAType
OrderCoreType.OriginalOrderAType.PriceQuotesAType.PriceQuoteAType
OrderPaymentFormType.PayerAType.NameAType
PinPhraseAnswerType
PolicyDefaultType.PolicyAType
PriceVarianceRuleNoticeType.QueryAType.PriceVarianceRuleAType.RuleIDAType
PriceVarianceRuleNoticeType.ResultsAType.PriceVarianceAType.RuleIDAType
ProgramStatusQualifier
PromotionQualifiers
RuleSetType.RuleSetIDAType
SeatAvailReqParamsType.PricingAType.FeeExemptionAType.FeeAType.CodeAType
ServiceFilter
ServiceOtherAssocType.OtherAssociationAType.TypeAType
SrvListReqParamsType.PricingAType.FeeExemptionAType.FeeAType.CodeAType
TaxDetailType.BreakdownAType.TaxAType.CollectionPointAType
TaxExemptionNoticeType.ResultsAType.TaxExemptionAType.RuleIDAType
TicketIdentificationType
TravelAgencyParticipantType
TravelerSummaryType.NameAType
Voucher.NameAType
```
